---
title: "wind_data"
author: "Jake Eisaguirre"
date: "5/5/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(raster)
library(sf)
library(lubridate)
library(ggquiver)
library(magick)
library(metR)
library(rCAT)
library(circular)

```


# download GFS u and v component of wind
```{r}



url_ucomp <- ("http://api.planetos.com/v1/datasets/noaa_gfs_pgrb2_global_forecast_recompute_0.25degree/area?polygon=[[-121.40,34.75],[-117.06,34.75],[-117.06,32.36],[-121.40,32.36],[-121.40,34.75]]&apikey=e5102ee5d77e422eaa5dea4124ba2165&csv=true&count=500000&variables=ugrd_m")

wind_u <- download.file(url_ucomp, here("data", "wind_u.csv"))

wind_u <- here("data", "wind_u.csv") %>% 
  read_csv()




url_vcomp <- "http://api.planetos.com/v1/datasets/noaa_gfs_pgrb2_global_forecast_recompute_0.25degree/area?polygon=[[-121.40,34.75],[-117.06,34.75],[-117.06,32.36],[-121.40,32.36],[-121.40,34.75]]&apikey=e5102ee5d77e422eaa5dea4124ba2165&csv=true&count=500000&variables=vgrd_m"

download.file(url_vcomp, here("data", "wind_v.csv"))

wind_v <- here("data", "wind_v.csv") %>% 
  read_csv()

```

```{r}
  wind_data <- left_join(wind_u, wind_v, by = c("axis:latitude", "axis:longitude"))
  
  wind_data <- wind_data %>% 
    as.data.frame() %>% 
    dplyr::select(!c("axis:time.y", "axis:reftime.y", "axis:z.y", "axis:z.x")) 
  
  names(wind_data) <- substring(names(wind_data), 6)
  
 wind_data$time.x <- as_datetime(wind_data$time.x)
 arrange(wind_data, desc(time.x))
 

 
plus3_day <- as.character(Sys.Date()+3) %>% 
  substring(8)

plus4_day <- as.character(Sys.Date()+4) %>% 
  substring(8)


 dates_string <- paste(c(paste(plus3_day, "03:00:00"), 
                         paste(plus3_day, "06:00:00"), paste(plus3_day, "09:00:00"),paste(plus3_day, "12:00:00"),
                         paste(plus3_day, "15:00:00"),paste(plus3_day, "18:00:00"), paste(plus3_day, "21:00:00"),
                         paste(plus3_day, "03:00:00"), paste(plus3_day, "06:00:00"), 
                         paste(plus3_day, "09:00:00"), paste(plus4_day, "12:00:00"),paste(plus4_day, "15:00:00"),
                         paste(plus4_day, "18:00:00"),paste(plus4_day, "21:00:00"),paste(plus4_day, "03:00:00"), 
                         paste(plus4_day, "06:00:00"), paste(plus4_day, "09:00:00")) , collapse = "|")
 
 
  wind_data_dates <- wind_data %>% 
    dplyr::select(!c(reftime.x)) %>% 
    rename(date = time.x) %>% 
    mutate(date = parse_date_time(date, "Ymd HMS", tz = "America/Los_Angeles" )) %>% 
    rename(u = `ugrd_m`) %>% 
    rename(v = `vgrd_m`) %>% 
    mutate(date = as.character(date)) %>% 
  filter(str_detect(date, paste(dates_string))) %>% 
  rename(x = longitude) %>% 
  rename(y = latitude)


wind_ras <- wind_data_dates %>%
  mutate(wind = ((sqrt((u^2) + (v^2)))),
         angle = atan2(u/wind, v/wind),
         angle = (angle * 180/pi),
         date = as.factor(date)) %>%
  dplyr::select(-c(u, v)) %>% 
  dplyr::select(x, everything()) %>% 
  relocate(wind, .before = date) %>% 
  mutate(wind = wind*1.94)

wind_angle <- wind_ras %>%
  dplyr::select(c("x", "y", "angle", "date", "wind")) %>% 
  group_by(x, y, date) %>% 
  summarize(angle = mean(circular(angle, type = "angles",units = "degrees", template = "clock24", rotation = "clock")),
         wind = mean(wind),
         x =x,
         y=y,
         date = date) %>% 
  mutate(angle = angle + 180)

wind_ras <- wind_ras %>% 
  dplyr::select(!c(angle))

date <-  unique(wind_ras$date)
```

```{r}

islands <- read_sf(here('data', "shape",'island_shape', "channel_islands.shp")) %>% 
  mutate(geometry = st_transform(geometry, crs = 4326))

ca <- read_sf(here('data', "shape","s_11au16", "s_11au16.shp")) %>% 
  mutate(geometry = st_transform(geometry, crs = 4326)) %>% 
  filter(NAME == "California") %>% 
  dplyr::select(geometry)

merged_shapes <- bind_rows(ca, islands)

```

```{r message=F, warning=F}


ras <- brick(xmn = -121.375,
             xmx = -117.125,
             ymn = 32.375,
             ymx = 34.875,
             nrows = 10,
             ncol = 17)

for(i in 1:length(levels(wind_ras$date))) {

  ras[[i]] <- wind_ras %>% 
    filter(date == levels(date)[i]) %>% 
    rasterFromXYZ() %>% 
    dropLayer(2)
}

names(ras) <-  date


```

```{r}

wind_res <- c(0.005, 0.005) 

new_ras_wind <- raster(xmn = -121.375,
             xmx = -117.125,
             ymn = 32.375,
             ymx = 34.875,
                      res = wind_res)

re_samp_wind <- resample(ras, new_ras_wind, method = "bilinear")

cropped_wind <- mask(re_samp_wind, merged_shapes, inverse = T)

final_ras_wind <- projectRaster(cropped_wind, crs = 4326)

```

# points
```{r}

wind_ras_data <- as.data.frame(rasterToPoints(final_ras_wind)) %>% 
  pivot_longer(!c(x,y), names_to = "date", values_to = "wind")


```

# pal
```{r}

wind_pal <- colorRampPalette(c( "#7635b8", "#3a57ba", "#4999b3","#5bc752", "#c9b84d", "#cc8247", "#ab3c4d", "#bf4182" ))

wind_limits <- c(0,50)

wind_values <- c(0, 10, 20, 30, 40, 50)

```


```{r}
wind.list = lapply(sort(unique(wind_ras_data$date)), function(i) {
  ggplot(data = wind_ras_data[wind_ras_data$date==i,], aes(y=y, x=x)) +
  geom_raster(aes(fill = wind), interpolate = T) +
  facet_wrap(~date) +
  scale_fill_gradientn(colours = wind_pal(100), limits = wind_limits, breaks = wind_values) +
  theme_classic() +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        plot.margin=unit(c(0,0,0,0), "null"),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  coord_sf(xlim = c(-121.45, -117.06), ylim = c(32.36, 34.75), expand = F)
})

wind.list[[2]]

```
```{r}
w_dpi <- c(215)

unlink("pngs/old/*")

for(i in 1:length(wind.list)){
  
  ggsave(paste0(here('pngs', 'old'), "/", wind_ras_data$date[i], '.png'), dpi = w_dpi, 
         bg = "transparent", plot = wind.list[[i]])
}
```

